// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVtHPtD51CBC_GuwnsJQ3V_usVL_8I-U0',
    appId: '1:538443592518:web:f84e58062f844f64b26b47',
    messagingSenderId: '538443592518',
    projectId: 'clarify-backend',
    authDomain: 'clarify-backend.firebaseapp.com',
    storageBucket: 'clarify-backend.appspot.com',
    measurementId: 'G-32SQPHXRFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW8y4mUfHoZ0sbfNM9WCPWVR7RNd1tbeM',
    appId: '1:538443592518:android:3d6059bc835dd78cb26b47',
    messagingSenderId: '538443592518',
    projectId: 'clarify-backend',
    storageBucket: 'clarify-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA3SFDvdYiAY6IHlxVo30Q7sUNsqVhWZs',
    appId: '1:538443592518:ios:b20795f16a0a9257b26b47',
    messagingSenderId: '538443592518',
    projectId: 'clarify-backend',
    storageBucket: 'clarify-backend.appspot.com',
    iosBundleId: 'com.example.clarifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA3SFDvdYiAY6IHlxVo30Q7sUNsqVhWZs',
    appId: '1:538443592518:ios:e07d3e91db6a3c1bb26b47',
    messagingSenderId: '538443592518',
    projectId: 'clarify-backend',
    storageBucket: 'clarify-backend.appspot.com',
    iosBundleId: 'com.example.clarifyApp.RunnerTests',
  );
}
